DO $$
declare type_id int;
val int;
ud record;  -- переменная для строки курсора
begin

if (SELECT count(id) FROM unload_package where id=69)>0 then
update unload_package set end_date='12.12.2018' where id=69;
end if;


if (SELECT count(id) FROM unload_package where id=72)=0 then
  insert into unload_package (id,code,name,unload_package_type_id,archive_format,zip_command,unzip_command,start_date) 
  select 72,'H','Пакет информационного обмена (версия 3.1)',1,'ZIP','7z a -tzip','7z x  -o','01.01.2018';
end if;

if (SELECT count(id) FROM unload_file where unload_package_id=72 and fl_main)=0 then
insert into unload_file (id,unload_package_id,name,title,version,code,file_type,fl_main,schema_address,code_page,dateformat,start_date) 
select 131,72,'ZL_LIST','Сведения об оказанной медицинской помощи','3.1','H','XML',true,'','','','01.01.2018';
end if;

if (SELECT count(id) FROM unload_file where unload_package_id=72 and code='L')=0 then
insert into unload_file (id,unload_package_id,name,title,version,code,file_type,fl_main,schema_address,code_page,dateformat,start_date) 
select 132,72,'PERS_LIST','Паспортная часть','3.1','L','XML',false,'','','','01.01.2018';
end if;
select setval('ambulance.unload_package_id_seq',(SELECT max(id) FROM unload_package)) into val;
select setval('ambulance.unload_file_id_seq',(SELECT max(id) FROM unload_file)) into val;
select setval('ambulance.unload_data_id_seq',(select max(mm) from (SELECT max(id) as mm FROM unload_data union select 9500 as mm) t)) into val;

FOR ud IN

select 9501 as cd,131 as unload_file_id,1 as order_num,'ZL_LIST' as name,'Корневой элемент' as description,null::int as unload_data_type_id,'' as length,'' as table_nm,'' as column_nm,1 as column_type,'' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9502 as cd,131 as unload_file_id,2 as order_num,'ZGLV' as name,'Заголовок файла' as description,null::int as unload_data_type_id,'' as length,'' as table_nm,'' as column_nm,1 as column_type,'ZL_LIST' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9503 as cd,131 as unload_file_id,3 as order_num,'SCHET' as name,'Счет' as description,null::int as unload_data_type_id,'' as length,'' as table_nm,'' as column_nm,1 as column_type,'ZL_LIST' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9504 as cd,131 as unload_file_id,4 as order_num,'ZAP' as name,'Записи' as description,null::int as unload_data_type_id,'' as length,'' as table_nm,'' as column_nm,6 as column_type,'ZL_LIST' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9505 as cd,131 as unload_file_id,5 as order_num,'VERSION' as name,'Версия взаимодействия' as description,1 as unload_data_type_id,'5' as length,'unload_file_attr42' as table_nm,'version' as column_nm,4 as column_type,'ZGLV' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9506 as cd,131 as unload_file_id,6 as order_num,'DATA' as name,'Дата формирования' as description,1 as unload_data_type_id,'10' as length,'unload_file_attr42' as table_nm,'data' as column_nm,4 as column_type,'ZGLV' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9507 as cd,131 as unload_file_id,7 as order_num,'FILENAME' as name,'Имя файла' as description,1 as unload_data_type_id,'32' as length,'unload_file_attr42' as table_nm,'filename' as column_nm,4 as column_type,'ZGLV' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9508 as cd,131 as unload_file_id,8 as order_num,'SD_Z' as name,'Количество случаев' as description,2 as unload_data_type_id,'9' as length,'unload_file_attr42' as table_nm,'sd_z' as column_nm,3 as column_type,'ZGLV' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,1 as group_teg 
union select 9509 as cd,131 as unload_file_id,9 as order_num,'CODE' as name,'Код записи счета' as description,2 as unload_data_type_id,'8' as length,'unload_file_attr42' as table_nm,'reestr_code' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9510 as cd,131 as unload_file_id,10 as order_num,'CODE_MO' as name,'Реестровый номер МО' as description,1 as unload_data_type_id,'6' as length,'unload_file_attr42' as table_nm,'code_MO' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9511 as cd,131 as unload_file_id,11 as order_num,'YEAR' as name,'Отчетный год' as description,2 as unload_data_type_id,'4' as length,'unload_file_attr42' as table_nm,'year' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9512 as cd,131 as unload_file_id,12 as order_num,'MONTH' as name,'Отчетный месяц' as description,2 as unload_data_type_id,'2' as length,'unload_file_attr42' as table_nm,'month' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9513 as cd,131 as unload_file_id,13 as order_num,'NSCHET' as name,'Номер счета' as description,1 as unload_data_type_id,'15' as length,'unload_file_attr42' as table_nm,'nschet' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9514 as cd,131 as unload_file_id,14 as order_num,'DSCHET' as name,'дата выставления счета' as description,1 as unload_data_type_id,'10' as length,'unload_file_attr42' as table_nm,'account_date' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9515 as cd,131 as unload_file_id,15 as order_num,'PLAT' as name,'Реестровый номер СМО' as description,1 as unload_data_type_id,'5' as length,'unload_file_attr42' as table_nm,'smo_reestr_code' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9516 as cd,131 as unload_file_id,16 as order_num,'SUMMAV' as name,'Сумма выставленная на оплату' as description,2 as unload_data_type_id,'15,2' as length,'unload_file_attr42' as table_nm,'summav' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9517 as cd,131 as unload_file_id,17 as order_num,'COMENTS' as name,'Служебное поле к счету' as description,1 as unload_data_type_id,'250' as length,'unload_file_attr42' as table_nm,'comments' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9518 as cd,131 as unload_file_id,18 as order_num,'SUMMAP' as name,'Сумма принятая на оплату' as description,2 as unload_data_type_id,'15,2' as length,'unload_file_attr42' as table_nm,'summap' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9519 as cd,131 as unload_file_id,19 as order_num,'SANK_MEK' as name,'Сумма, снятая с оплаты после МЭК' as description,2 as unload_data_type_id,'15,2' as length,'unload_file_attr42' as table_nm,'sank_mek' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9520 as cd,131 as unload_file_id,20 as order_num,'SANK_MEE' as name,'Сумма, снятая с оплаты после МЭЭ' as description,2 as unload_data_type_id,'15,2' as length,'unload_file_attr42' as table_nm,'sank_mee' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9521 as cd,131 as unload_file_id,21 as order_num,'SANK_EKMP' as name,'Сумма, снятая с оплаты после ЭКМП' as description,2 as unload_data_type_id,'15,2' as length,'unload_file_attr42' as table_nm,'sank_ekmp' as column_nm,null as column_type,'SCHET' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9522 as cd,131 as unload_file_id,22 as order_num,'N_ZAP' as name,'Номер позиции записи' as description,2 as unload_data_type_id,'8' as length,'unload_calls42' as table_nm,'n_zap' as column_nm,3 as column_type,'ZAP' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,1 as group_teg 
union select 9523 as cd,131 as unload_file_id,23 as order_num,'PR_NOV' as name,'Признак исправленной записи' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'pr_nov' as column_nm,3 as column_type,'ZAP' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,1 as group_teg 
union select 9524 as cd,131 as unload_file_id,24 as order_num,'PACIENT' as name,'Сведения о пациенте' as description,2 as unload_data_type_id,'8' as length,'' as table_nm,'n_zap' as column_nm,6 as column_type,'ZAP' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9525 as cd,131 as unload_file_id,25 as order_num,'Z_SL' as name,'Сведения о законченном случае' as description,2 as unload_data_type_id,'8' as length,'' as table_nm,'n_zap' as column_nm,6 as column_type,'ZAP' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9526 as cd,131 as unload_file_id,26 as order_num,'FLK' as name,'Сведения о пациенте' as description,2 as unload_data_type_id,'8' as length,'' as table_nm,'n_zap' as column_nm,6 as column_type,'ZAP' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9527 as cd,131 as unload_file_id,27 as order_num,'ID_PAC' as name,'Код записи о пациенте' as description,1 as unload_data_type_id,'36' as length,'unload_calls42' as table_nm,'PID' as column_nm,3 as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9528 as cd,131 as unload_file_id,28 as order_num,'VPOLIS' as name,'Тип полиса' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'vpolis' as column_nm,4 as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9529 as cd,131 as unload_file_id,29 as order_num,'SPOLIS' as name,'Серия полиса' as description,1 as unload_data_type_id,'10' as length,'unload_calls42' as table_nm,'polis_serial' as column_nm,4 as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9530 as cd,131 as unload_file_id,30 as order_num,'NPOLIS' as name,'Номер полиса' as description,1 as unload_data_type_id,'20' as length,'unload_calls42' as table_nm,'polis_num' as column_nm,4 as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9531 as cd,131 as unload_file_id,31 as order_num,'ST_OKATO' as name,'Регион страхования' as description,1 as unload_data_type_id,'5' as length,'unload_calls42' as table_nm,'st_okato' as column_nm,4 as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,2 as need,'vpolis is not null' as check_text,2 as group_teg 
union select 9532 as cd,131 as unload_file_id,32 as order_num,'SMO' as name,'Реестровый номер СМО' as description,1 as unload_data_type_id,'5' as length,'unload_calls42' as table_nm,'smo_reestr_code' as column_nm,4 as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9533 as cd,131 as unload_file_id,33 as order_num,'SMO_OGRN' as name,'ОГРН СМО' as description,1 as unload_data_type_id,'15' as length,'unload_calls42' as table_nm,'smo_ogrn' as column_nm,null as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9534 as cd,131 as unload_file_id,34 as order_num,'SMO_OK' as name,'ОКАТО страхования' as description,1 as unload_data_type_id,'5' as length,'unload_calls42' as table_nm,'smo_okato' as column_nm,null as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9535 as cd,131 as unload_file_id,35 as order_num,'SMO_NAM' as name,'Наименование СМО' as description,1 as unload_data_type_id,'100' as length,'unload_calls42' as table_nm,'smo_name' as column_nm,null as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9536 as cd,131 as unload_file_id,36 as order_num,'NOVOR' as name,'Признак новорожденного' as description,1 as unload_data_type_id,'9' as length,'unload_calls42' as table_nm,'przn_novor' as column_nm,3 as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9537 as cd,131 as unload_file_id,37 as order_num,'VNOV_D' as name,'Вес при рождении' as description,2 as unload_data_type_id,'4' as length,'' as table_nm,'' as column_nm,null as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9538 as cd,131 as unload_file_id,38 as order_num,'MO_ATTACH' as name,'Код МО(СМП), прикрепления пациента' as description,1 as unload_data_type_id,'6' as length,'' as table_nm,'' as column_nm,null as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9539 as cd,131 as unload_file_id,39 as order_num,'PODR_ATTACH' as name,'Код подразделения прикрепления пациента' as description,1 as unload_data_type_id,'6' as length,'' as table_nm,'' as column_nm,null as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9540 as cd,131 as unload_file_id,40 as order_num,'MO_HOSP' as name,'Код МО, госпитализации' as description,1 as unload_data_type_id,'6' as length,'unload_calls42' as table_nm,'kod_mo_gosp' as column_nm,4 as column_type,'PACIENT' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9541 as cd,131 as unload_file_id,41 as order_num,'IDCASE' as name,'Номер записи в реестре случаев' as description,2 as unload_data_type_id,'16' as length,'unload_calls42' as table_nm,'cd' as column_nm,3 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9542 as cd,131 as unload_file_id,42 as order_num,'ID_TF' as name,'Идентификатор случая в базе ТФОМС' as description,2 as unload_data_type_id,'19' as length,'' as table_nm,'' as column_nm,null as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9543 as cd,131 as unload_file_id,43 as order_num,'USL_OK' as name,'Условия оказания медицинской помощи' as description,2 as unload_data_type_id,'2' as length,'unload_calls42' as table_nm,'usl_ok' as column_nm,3 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9544 as cd,131 as unload_file_id,44 as order_num,'VIDPOM' as name,'Вид помощи' as description,2 as unload_data_type_id,'4' as length,'unload_calls42' as table_nm,'vid_pom' as column_nm,3 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9545 as cd,131 as unload_file_id,45 as order_num,'FOR_POM' as name,'Форма оказания медицинской помощи' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'for_pom' as column_nm,3 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9546 as cd,131 as unload_file_id,46 as order_num,'NPR_MO' as name,'Код МО, направившего на лечение' as description,1 as unload_data_type_id,'6' as length,'unload_calls42' as table_nm,'npr_mo' as column_nm,4 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9547 as cd,131 as unload_file_id,47 as order_num,'NPR_PODR' as name,'Код подразделения МО, направившего на лечение' as description,1 as unload_data_type_id,'6' as length,'' as table_nm,'' as column_nm,null as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9548 as cd,131 as unload_file_id,48 as order_num,'NPR_DATE' as name,'Дата направления на лечение' as description,1 as unload_data_type_id,'10' as length,'' as table_nm,'' as column_nm,null as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9549 as cd,131 as unload_file_id,49 as order_num,'LPU' as name,'Код МО' as description,1 as unload_data_type_id,'6' as length,'unload_calls42' as table_nm,'LPU_code' as column_nm,3 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9550 as cd,131 as unload_file_id,50 as order_num,'DATE_Z_1' as name,'Дата начала лечения' as description,1 as unload_data_type_id,'10' as length,'unload_calls42' as table_nm,'date_z_1' as column_nm,3 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9551 as cd,131 as unload_file_id,51 as order_num,'DATE_Z_2' as name,'Дата окончания лечения' as description,1 as unload_data_type_id,'10' as length,'unload_calls42' as table_nm,'date_f' as column_nm,3 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9552 as cd,131 as unload_file_id,52 as order_num,'VNOV_M' as name,'Вес при рождении' as description,2 as unload_data_type_id,'4' as length,'' as table_nm,'' as column_nm,null as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9553 as cd,131 as unload_file_id,53 as order_num,'RSLT' as name,'Результат обращения' as description,2 as unload_data_type_id,'3' as length,'unload_calls42' as table_nm,'call_result' as column_nm,3 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9554 as cd,131 as unload_file_id,54 as order_num,'ISHOD' as name,'Исход заболевания' as description,2 as unload_data_type_id,'3' as length,'unload_calls42' as table_nm,'measure_code' as column_nm,3 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9555 as cd,131 as unload_file_id,55 as order_num,'OS_SLUCH' as name,'Особый случай' as description,2 as unload_data_type_id,'16' as length,'' as table_nm,'cd' as column_nm,6 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9556 as cd,131 as unload_file_id,56 as order_num,'OS_SLUCH' as name,'Признак особый случай' as description,2 as unload_data_type_id,'1' as length,'unload_special_case' as table_nm,'OS_SLUCH_CODE' as column_nm,4 as column_type,'OS_SLUCH' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9557 as cd,131 as unload_file_id,57 as order_num,'SL' as name,'Сведения о случае' as description,2 as unload_data_type_id,'16' as length,'' as table_nm,'cd' as column_nm,6 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9558 as cd,131 as unload_file_id,58 as order_num,'SL_ID' as name,'Идентификатор' as description,1 as unload_data_type_id,'36' as length,'unload_calls42' as table_nm,'IDSERV' as column_nm,4 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9559 as cd,131 as unload_file_id,59 as order_num,'LPU_1' as name,'Подразделение МО' as description,1 as unload_data_type_id,'8' as length,'' as table_nm,'' as column_nm,null as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9560 as cd,131 as unload_file_id,60 as order_num,'PODR' as name,'Код отделения' as description,2 as unload_data_type_id,'8' as length,'' as table_nm,'' as column_nm,null as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9561 as cd,131 as unload_file_id,61 as order_num,'PROFIL' as name,'Профиль оказанной помощи' as description,2 as unload_data_type_id,'3' as length,'unload_calls42' as table_nm,'profil' as column_nm,3 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9562 as cd,131 as unload_file_id,62 as order_num,'DET' as name,'Признак детского профиля' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'det_przn' as column_nm,3 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9563 as cd,131 as unload_file_id,63 as order_num,'NHISTORY' as name,'Номер талона' as description,1 as unload_data_type_id,'50' as length,'unload_calls42' as table_nm,'kt_num' as column_nm,3 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9564 as cd,131 as unload_file_id,64 as order_num,'P_PER' as name,'Признак поступления/перевода' as description,2 as unload_data_type_id,'1' as length,'' as table_nm,'' as column_nm,null as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9565 as cd,131 as unload_file_id,65 as order_num,'DATE_1' as name,'Дата начала лечения' as description,1 as unload_data_type_id,'21' as length,'unload_calls42' as table_nm,'time_go' as column_nm,3 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9566 as cd,131 as unload_file_id,66 as order_num,'DATE_2' as name,'Дата окончания лечения' as description,1 as unload_data_type_id,'21' as length,'unload_calls42' as table_nm,'time_arrive' as column_nm,3 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9567 as cd,131 as unload_file_id,67 as order_num,'DS0' as name,'Диагноз первичный' as description,1 as unload_data_type_id,'10' as length,'unload_calls42' as table_nm,'ds0' as column_nm,4 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9568 as cd,131 as unload_file_id,68 as order_num,'DS1' as name,'Диагноз основной' as description,1 as unload_data_type_id,'10' as length,'unload_calls42' as table_nm,'diag_mkb1' as column_nm,3 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9569 as cd,131 as unload_file_id,69 as order_num,'DS2' as name,'Диагноз сопутствующий' as description,1 as unload_data_type_id,'10' as length,'unload_calls42' as table_nm,'diag_mkb2' as column_nm,4 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9570 as cd,131 as unload_file_id,70 as order_num,'DS3' as name,'Диагноз осложнения' as description,1 as unload_data_type_id,'10' as length,'unload_calls42' as table_nm,'' as column_nm,null as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9571 as cd,131 as unload_file_id,71 as order_num,'C_ZAB' as name,'Характер основного заболевания' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'C_ZAB' as column_nm,4 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9572 as cd,131 as unload_file_id,72 as order_num,'DS_ONK' as name,'Признак подозрения на злокачественное новообразование' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'ds_onk' as column_nm,4 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9573 as cd,131 as unload_file_id,73 as order_num,'CODE_MES1' as name,'Код МЭС' as description,1 as unload_data_type_id,'20' as length,'unload_calls42' as table_nm,'code_mes1' as column_nm,4 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9574 as cd,131 as unload_file_id,74 as order_num,'CODE_MES2' as name,'Код МЭС сопутствующего заболевания' as description,1 as unload_data_type_id,'20' as length,'unload_calls42' as table_nm,'code_mes2' as column_nm,4 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9575 as cd,131 as unload_file_id,75 as order_num,'CONS' as name,'Сведения о проведении консилиума' as description,2 as unload_data_type_id,'11' as length,'' as table_nm,'cd' as column_nm,6 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9576 as cd,131 as unload_file_id,76 as order_num,'PR_CONS' as name,'Цель проведения консилиума' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'PR_CONS' as column_nm,4 as column_type,'CONS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9577 as cd,131 as unload_file_id,77 as order_num,'ONK_SL' as name,'Сведения о случае лечения онкологического заболевания' as description,2 as unload_data_type_id,'11' as length,'' as table_nm,'cd' as column_nm,6 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9578 as cd,131 as unload_file_id,78 as order_num,'STAD' as name,'Стадия заболевания' as description,2 as unload_data_type_id,'3' as length,'unload_onk42' as table_nm,'stad' as column_nm,null as column_type,'ONK_SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'(substring(diag_mkb1,1,1)=''C'' or substring(diag_mkb1,1,2)=''D0'' or substring(diag_mkb1,1,3)=''D70'') and COALESCE(ds_onk,0)<>1' as check_text,2 as group_teg 
union select 9579 as cd,131 as unload_file_id,79 as order_num,'ONK_T' as name,'Значение Tumor' as description,2 as unload_data_type_id,'3' as length,'unload_onk42' as table_nm,'tumor' as column_nm,null as column_type,'ONK_SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'(substring(diag_mkb1,1,1)=''C'' or substring(diag_mkb1,1,2)=''D0'' or substring(diag_mkb1,1,3)=''D70'') and COALESCE(ds_onk,0)<>1' as check_text,2 as group_teg 
union select 9580 as cd,131 as unload_file_id,80 as order_num,'ONK_N' as name,'Значение Nodus' as description,2 as unload_data_type_id,'3' as length,'unload_onk42' as table_nm,'nodus' as column_nm,null as column_type,'ONK_SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'(substring(diag_mkb1,1,1)=''C'' or substring(diag_mkb1,1,2)=''D0'' or substring(diag_mkb1,1,3)=''D70'') and COALESCE(ds_onk,0)<>1' as check_text,2 as group_teg 
union select 9581 as cd,131 as unload_file_id,81 as order_num,'ONK_M' as name,'Значение Metastasis' as description,2 as unload_data_type_id,'3' as length,'unload_onk42' as table_nm,'Metastasis' as column_nm,null as column_type,'ONK_SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'(substring(diag_mkb1,1,1)=''C'' or substring(diag_mkb1,1,2)=''D0'' or substring(diag_mkb1,1,3)=''D70'') and COALESCE(ds_onk,0)<>1' as check_text,2 as group_teg 
union select 9582 as cd,131 as unload_file_id,82 as order_num,'PRVS' as name,'Специальность лечащего врача' as description,2 as unload_data_type_id,'4' as length,'unload_calls42' as table_nm,'emp_spec_code' as column_nm,3 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9583 as cd,131 as unload_file_id,83 as order_num,'VERS_SPEC' as name,'Код классификатора медицинских специальностей' as description,1 as unload_data_type_id,'4' as length,'unload_calls42' as table_nm,'vers_spec' as column_nm,4 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9584 as cd,131 as unload_file_id,84 as order_num,'IDDOKT' as name,'Код врача закрывшего талон' as description,1 as unload_data_type_id,'25' as length,'unload_calls42' as table_nm,'emp_snils' as column_nm,3 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9585 as cd,131 as unload_file_id,85 as order_num,'ED_COL' as name,'Количество единиц оплаты МП' as description,2 as unload_data_type_id,'5,2' as length,'unload_calls42' as table_nm,'ed_col' as column_nm,4 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9586 as cd,131 as unload_file_id,86 as order_num,'TARIF' as name,'Тариф' as description,2 as unload_data_type_id,'15,2' as length,'unload_calls42' as table_nm,'tarif' as column_nm,4 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9587 as cd,131 as unload_file_id,87 as order_num,'SUM_M' as name,'Стоимость случая, выставленная к оплате' as description,2 as unload_data_type_id,'15,2' as length,'unload_calls42' as table_nm,'sumv' as column_nm,null as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9588 as cd,131 as unload_file_id,88 as order_num,'USL' as name,'Сведения об услуге' as description,2 as unload_data_type_id,'11' as length,'' as table_nm,'cd' as column_nm,6 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9589 as cd,131 as unload_file_id,89 as order_num,'COMENTSL' as name,'Служебное поле' as description,1 as unload_data_type_id,'250' as length,'unload_calls42' as table_nm,'comentsl' as column_nm,4 as column_type,'SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9590 as cd,131 as unload_file_id,90 as order_num,'IDSP' as name,'Код способа оплаты' as description,2 as unload_data_type_id,'2' as length,'unload_calls42' as table_nm,'idsp' as column_nm,3 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9591 as cd,131 as unload_file_id,91 as order_num,'SUMV' as name,'Сумма на оплату' as description,2 as unload_data_type_id,'15,2' as length,'unload_calls42' as table_nm,'sumv' as column_nm,null as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9592 as cd,131 as unload_file_id,92 as order_num,'OPLATA' as name,'Тип оплаты' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'oplata' as column_nm,4 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9593 as cd,131 as unload_file_id,93 as order_num,'SUMP' as name,'Сумма принятая на оплату' as description,2 as unload_data_type_id,'15,2' as length,'unload_calls42' as table_nm,'sump' as column_nm,4 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9594 as cd,131 as unload_file_id,94 as order_num,'SANK' as name,'Сведения о санкциях' as description,2 as unload_data_type_id,'11' as length,'' as table_nm,'cd' as column_nm,6 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9595 as cd,131 as unload_file_id,95 as order_num,'SANK_IT' as name,'Сумма санкций по случаю' as description,2 as unload_data_type_id,'15,2' as length,'unload_calls42' as table_nm,'SANK_IT' as column_nm,4 as column_type,'Z_SL' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9596 as cd,131 as unload_file_id,96 as order_num,'S_CODE' as name,'Идентификатор санкции' as description,1 as unload_data_type_id,'36' as length,'unload_calls42' as table_nm,'S_CODE' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9597 as cd,131 as unload_file_id,97 as order_num,'S_SUM' as name,'Финансовая санкция' as description,2 as unload_data_type_id,'15,2' as length,'unload_calls42' as table_nm,'S_SUM' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9598 as cd,131 as unload_file_id,98 as order_num,'S_FINE' as name,'Сумма штрафа' as description,2 as unload_data_type_id,'15,2' as length,'unload_calls42' as table_nm,'S_FINE' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9599 as cd,131 as unload_file_id,99 as order_num,'S_TIP' as name,'Тип санкции' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'S_TIP' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9600 as cd,131 as unload_file_id,100 as order_num,'SL_ID' as name,'Идентификатор случая' as description,1 as unload_data_type_id,'36' as length,'unload_calls42' as table_nm,'SL_ID' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9601 as cd,131 as unload_file_id,101 as order_num,'S_OSN' as name,'Код причины отказа оплаты' as description,2 as unload_data_type_id,'3' as length,'unload_calls42' as table_nm,'S_OSN' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9602 as cd,131 as unload_file_id,102 as order_num,'DATE_ACT' as name,'Дата акта МЭК,МЭЭ или ЭКМП' as description,1 as unload_data_type_id,'10' as length,'unload_calls42' as table_nm,'DATE_ACT' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9603 as cd,131 as unload_file_id,103 as order_num,'NUM_ACT' as name,'Номер акта МЭК,МЭЭ или ЭКМП' as description,1 as unload_data_type_id,'30' as length,'unload_calls42' as table_nm,'NUM_ACT' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9604 as cd,131 as unload_file_id,104 as order_num,'CODE_EXP' as name,'Код эксперта качества медицинской помощи' as description,1 as unload_data_type_id,'8' as length,'unload_calls42' as table_nm,'CODE_EXP' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9605 as cd,131 as unload_file_id,105 as order_num,'S_COM' as name,'Комментарий' as description,1 as unload_data_type_id,'250' as length,'unload_calls42' as table_nm,'S_COM' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9606 as cd,131 as unload_file_id,106 as order_num,'S_IST' as name,'Источник' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'S_IST' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9607 as cd,131 as unload_file_id,107 as order_num,'OBJECTIVE' as name,'Признак,что экспертиза не проведена в сроки по объект.прич.' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'OBJECTIVE' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9608 as cd,131 as unload_file_id,108 as order_num,'MD_EXP' as name,'Признак мультидисципли-нарной ЭКМП' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'MD_EXP' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9609 as cd,131 as unload_file_id,109 as order_num,'META_EXP' as name,'Признак метаэкспертизы' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'META_EXP' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9610 as cd,131 as unload_file_id,110 as order_num,'FINISHED' as name,'Признак завершенной экспертизы' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'FINISHED' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9611 as cd,131 as unload_file_id,111 as order_num,'DF_PER_EX' as name,'Отчетный период предоставления экспертизы' as description,2 as unload_data_type_id,'1' as length,'unload_calls42' as table_nm,'DF_PER_EX' as column_nm,null as column_type,'SANK' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9612 as cd,131 as unload_file_id,112 as order_num,'IDSERV' as name,'Номер записи в реестре услуг' as description,1 as unload_data_type_id,'36' as length,'unload_usl' as table_nm,'IDSERV' as column_nm,3 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9613 as cd,131 as unload_file_id,113 as order_num,'LPU' as name,'Код МО' as description,1 as unload_data_type_id,'6' as length,'unload_usl' as table_nm,'LPU_code' as column_nm,3 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9614 as cd,131 as unload_file_id,114 as order_num,'LPU_1' as name,'Подразделение МО' as description,1 as unload_data_type_id,'8' as length,'unload_usl' as table_nm,'' as column_nm,null as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9615 as cd,131 as unload_file_id,115 as order_num,'PODR' as name,'Код отделения' as description,2 as unload_data_type_id,'8' as length,'unload_usl' as table_nm,'' as column_nm,null as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9616 as cd,131 as unload_file_id,116 as order_num,'PROFIL' as name,'Профиль' as description,2 as unload_data_type_id,'3' as length,'unload_usl' as table_nm,'profil' as column_nm,3 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9617 as cd,131 as unload_file_id,117 as order_num,'VID_VME' as name,'Вид медицинского вмешательства' as description,1 as unload_data_type_id,'15' as length,'unload_usl' as table_nm,'CODE_USL' as column_nm,4 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9618 as cd,131 as unload_file_id,118 as order_num,'DET' as name,'Признак детского профиля' as description,2 as unload_data_type_id,'1' as length,'unload_usl' as table_nm,'det_przn' as column_nm,3 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9619 as cd,131 as unload_file_id,119 as order_num,'DATE_IN' as name,'Дата начала оказания услуги' as description,1 as unload_data_type_id,'10' as length,'unload_usl' as table_nm,'date_s' as column_nm,3 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9620 as cd,131 as unload_file_id,120 as order_num,'DATE_OUT' as name,'Дата окончания оказания услуги' as description,1 as unload_data_type_id,'10' as length,'unload_usl' as table_nm,'date_f' as column_nm,3 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9621 as cd,131 as unload_file_id,121 as order_num,'DS' as name,'Диагноз' as description,1 as unload_data_type_id,'10' as length,'unload_usl' as table_nm,'diag_mkb1' as column_nm,3 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9622 as cd,131 as unload_file_id,122 as order_num,'CODE_USL' as name,'Код услуги' as description,1 as unload_data_type_id,'20' as length,'unload_usl' as table_nm,'CODE' as column_nm,3 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9623 as cd,131 as unload_file_id,123 as order_num,'KOL_USL' as name,'Количество услуг (кратность услуги)' as description,2 as unload_data_type_id,'6,2' as length,'unload_usl' as table_nm,'KOL_USL' as column_nm,3 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9624 as cd,131 as unload_file_id,124 as order_num,'TARIF' as name,'Тариф' as description,2 as unload_data_type_id,'15,2' as length,'unload_usl' as table_nm,'' as column_nm,null as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9625 as cd,131 as unload_file_id,125 as order_num,'SUMV_USL' as name,'Стоимость медицинской услуги, принятая к оплате (руб.)' as description,2 as unload_data_type_id,'15,2' as length,'unload_usl' as table_nm,'sumv' as column_nm,3 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9626 as cd,131 as unload_file_id,126 as order_num,'PRVS' as name,'Специальность медработника, выполнившего услугу' as description,2 as unload_data_type_id,'9' as length,'unload_usl' as table_nm,'emp_spec_code' as column_nm,3 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9627 as cd,131 as unload_file_id,127 as order_num,'CODE_MD' as name,'Код медицинского работника, оказавшего медицинскую услугу' as description,1 as unload_data_type_id,'25' as length,'unload_usl' as table_nm,'emp_snils' as column_nm,3 as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9628 as cd,131 as unload_file_id,128 as order_num,'NPL' as name,'Неполный объем' as description,2 as unload_data_type_id,'1' as length,'unload_usl' as table_nm,'' as column_nm,null as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9629 as cd,131 as unload_file_id,129 as order_num,'COMENTU' as name,'Служебное поле' as description,1 as unload_data_type_id,'250' as length,'unload_usl' as table_nm,'' as column_nm,null as column_type,'USL' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9630 as cd,131 as unload_file_id,130 as order_num,'ERR' as name,'Ошибки ФЛК' as description,2 as unload_data_type_id,'8' as length,'' as table_nm,'n_zap' as column_nm,6 as column_type,'FLK' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9631 as cd,131 as unload_file_id,131 as order_num,'ERR' as name,'Ошибки ФЛК' as description,2 as unload_data_type_id,'3' as length,'unload_calls42' as table_nm,'ERR' as column_nm,null as column_type,'ERR' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9632 as cd,131 as unload_file_id,132 as order_num,'COMM' as name,'Комментарий к ошибке' as description,1 as unload_data_type_id,'250' as length,'unload_calls42' as table_nm,'COMM' as column_nm,null as column_type,'ERR' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 

LOOP
       if (select count(*) from unload_data where unload_file_id=131 and name=ud.name and db_table_nm=ud.db_table_nm)=0 then
	insert into unload_data (id,unload_file_id,order_num,name,description,unload_data_type_id,length,table_nm,column_nm,unload_column_type_id,db_table_nm,fl_update,update_str,need,check_text,group_teg,fl_const,start_date)
	select ud.cd,ud.unload_file_id,ud.order_num,ud.name,ud.description,ud.unload_data_type_id,ud.length,ud.table_nm,ud.column_nm,ud.column_type,ud.db_table_nm,case when ud.fl_update is null then false else true end,ud.update_str,
	case when ud.need=1 then true when ud.need=3 then false else null end,ud.check_text,ud.group_teg,false,'01.01.2018';
       end if;
    END LOOP;
FOR ud IN
select 9651 as cd,132 as unload_file_id,1 as order_num,'PERS_LIST' as name,'Корневой элемент' as description,null::int as unload_data_type_id,'' as length,'' as table_nm,'' as column_nm,1 as column_type,'' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9652 as cd,132 as unload_file_id,2 as order_num,'ZGLV' as name,'Заголовок файла' as description,null::int as unload_data_type_id,'' as length,'' as table_nm,'' as column_nm,1 as column_type,'PERS_LIST' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,1 as group_teg 
union select 9653 as cd,132 as unload_file_id,3 as order_num,'PERS' as name,'Данные' as description,null::int as unload_data_type_id,'' as length,'' as table_nm,'' as column_nm,6 as column_type,'PERS_LIST' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9654 as cd,132 as unload_file_id,4 as order_num,'VERSION' as name,'Версия взаимодействия' as description,1 as unload_data_type_id,'5' as length,'unload_file_attr' as table_nm,'version' as column_nm,4 as column_type,'ZGLV' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9655 as cd,132 as unload_file_id,5 as order_num,'DATA' as name,'Дата' as description,1 as unload_data_type_id,'10' as length,'unload_file_attr' as table_nm,'data' as column_nm,4 as column_type,'ZGLV' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9656 as cd,132 as unload_file_id,6 as order_num,'FILENAME' as name,'Имя файла' as description,1 as unload_data_type_id,'26' as length,'unload_file_attr' as table_nm,'filename' as column_nm,4 as column_type,'ZGLV' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9657 as cd,132 as unload_file_id,7 as order_num,'FILENAME1' as name,'Имя основного файла' as description,1 as unload_data_type_id,'26' as length,'unload_file_attr' as table_nm,'filename1' as column_nm,4 as column_type,'ZGLV' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9658 as cd,132 as unload_file_id,8 as order_num,'ID_PAC' as name,'Код записи о пациенте' as description,1 as unload_data_type_id,'36' as length,'unload_PID' as table_nm,'PID' as column_nm,3 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,1 as need,'' as check_text,2 as group_teg 
union select 9659 as cd,132 as unload_file_id,9 as order_num,'FAM' as name,'Фамилия пациента' as description,1 as unload_data_type_id,'40' as length,'unload_PID' as table_nm,'FAM' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'COALESCE(fl_patient_represent,0)=0 and sc_code2 is null' as check_text,2 as group_teg 
union select 9660 as cd,132 as unload_file_id,10 as order_num,'IM' as name,'Имя пациента' as description,1 as unload_data_type_id,'40' as length,'unload_PID' as table_nm,'IM' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'COALESCE(fl_patient_represent,0)=0 and sc_code3 is null' as check_text,2 as group_teg 
union select 9661 as cd,132 as unload_file_id,11 as order_num,'OT' as name,'Отчество пациента' as description,1 as unload_data_type_id,'40' as length,'unload_PID' as table_nm,'OT' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'COALESCE(fl_patient_represent,0)=0 and sc_code1 is null' as check_text,2 as group_teg 
union select 9662 as cd,132 as unload_file_id,12 as order_num,'W' as name,'Пол пациента' as description,2 as unload_data_type_id,'1' as length,'unload_PID' as table_nm,'sex_code' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9663 as cd,132 as unload_file_id,13 as order_num,'DR' as name,'Дата рождения пациента' as description,1 as unload_data_type_id,'10' as length,'unload_PID' as table_nm,'DR' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'sc_code6 is null' as check_text,2 as group_teg 
union select 9664 as cd,132 as unload_file_id,14 as order_num,'DOST' as name,'Надежность идентификации' as description,1 as unload_data_type_id,'36' as length,'' as table_nm,'PID' as column_nm,6 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9665 as cd,132 as unload_file_id,15 as order_num,'DOST' as name,'Код надежности идентификации' as description,2 as unload_data_type_id,'1' as length,'unload_special_case' as table_nm,'DOST_CODE' as column_nm,4 as column_type,'DOST' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9666 as cd,132 as unload_file_id,16 as order_num,'TEL' as name,'Номер телефона пациента' as description,1 as unload_data_type_id,'10' as length,'unload_PID' as table_nm,'' as column_nm,null as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9667 as cd,132 as unload_file_id,17 as order_num,'FAM_P' as name,'Фамилия представителя' as description,1 as unload_data_type_id,'40' as length,'unload_PID' as table_nm,'FAM_P' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'fl_patient_represent=1 and sc_code2 is null' as check_text,2 as group_teg 
union select 9668 as cd,132 as unload_file_id,18 as order_num,'IM_P' as name,'Имя представителя' as description,1 as unload_data_type_id,'40' as length,'unload_PID' as table_nm,'IM_P' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'fl_patient_represent=1 and sc_code3 is null' as check_text,2 as group_teg 
union select 9669 as cd,132 as unload_file_id,19 as order_num,'OT_P' as name,'Отчество представителя' as description,1 as unload_data_type_id,'40' as length,'unload_PID' as table_nm,'OT_P' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'fl_patient_represent=1 and sc_code1 is null' as check_text,2 as group_teg 
union select 9670 as cd,132 as unload_file_id,20 as order_num,'W_P' as name,'Пол представителя' as description,2 as unload_data_type_id,'1' as length,'unload_PID' as table_nm,'sex_code_P' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'fl_patient_represent=1' as check_text,2 as group_teg 
union select 9671 as cd,132 as unload_file_id,21 as order_num,'DR_P' as name,'Дата рождения представителя' as description,1 as unload_data_type_id,'10' as length,'unload_PID' as table_nm,'DR_P' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'fl_patient_represent=1' as check_text,2 as group_teg 
union select 9672 as cd,132 as unload_file_id,22 as order_num,'DOST_P' as name,'Надежность идентификации представителя' as description,1 as unload_data_type_id,'36' as length,'' as table_nm,'PID' as column_nm,6 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9673 as cd,132 as unload_file_id,23 as order_num,'DOST_P' as name,'Код надежности идентификации' as description,2 as unload_data_type_id,'1' as length,'unload_special_case' as table_nm,'DOST_P_CODE' as column_nm,4 as column_type,'DOST_P' as db_table_nm,null as fl_update,'' as update_str,3 as need,'' as check_text,2 as group_teg 
union select 9674 as cd,132 as unload_file_id,24 as order_num,'MR' as name,'Место рождения пациента или представителя' as description,1 as unload_data_type_id,'100' as length,'unload_PID' as table_nm,'mr' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9675 as cd,132 as unload_file_id,25 as order_num,'DOCTYPE' as name,'Тип документа' as description,1 as unload_data_type_id,'2' as length,'unload_PID' as table_nm,'doctype' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'COALESCE(vpolis,0) not in (2,3) and COALESCE(substring(smo_reestr_code,1,2),''00'')<>''42''' as check_text,2 as group_teg 
union select 9676 as cd,132 as unload_file_id,26 as order_num,'DOCSER' as name,'Серия документа' as description,1 as unload_data_type_id,'10' as length,'unload_PID' as table_nm,'docser' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'COALESCE(vpolis,0) not in (2,3) and COALESCE(substring(smo_reestr_code,1,2),''00'')<>''42''' as check_text,2 as group_teg 
union select 9677 as cd,132 as unload_file_id,27 as order_num,'DOCNUM' as name,'Номер документа' as description,1 as unload_data_type_id,'20' as length,'unload_PID' as table_nm,'docnum' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'COALESCE(vpolis,0) not in (2,3) and COALESCE(substring(smo_reestr_code,1,2),''00'')<>''42''' as check_text,2 as group_teg 
union select 9678 as cd,132 as unload_file_id,28 as order_num,'SNILS' as name,'СНИЛС' as description,1 as unload_data_type_id,'14' as length,'unload_PID' as table_nm,'snils' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9679 as cd,132 as unload_file_id,29 as order_num,'OKATOG' as name,'Код места жительства' as description,1 as unload_data_type_id,'11' as length,'unload_PID' as table_nm,'okatog' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9680 as cd,132 as unload_file_id,30 as order_num,'OKATOP' as name,'Код места пребывания по ОКАТО' as description,1 as unload_data_type_id,'11' as length,'unload_PID' as table_nm,'okatop' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 
union select 9681 as cd,132 as unload_file_id,31 as order_num,'COMENTP' as name,'Служебное поле' as description,1 as unload_data_type_id,'250' as length,'unload_PID' as table_nm,'comentp' as column_nm,4 as column_type,'PERS' as db_table_nm,null as fl_update,'' as update_str,2 as need,'' as check_text,2 as group_teg 

    LOOP
       if (select count(*) from unload_data where unload_file_id=132 and name=ud.name and db_table_nm=ud.db_table_nm)=0 then
	insert into unload_data (id,unload_file_id,order_num,name,description,unload_data_type_id,length,table_nm,column_nm,unload_column_type_id,db_table_nm,fl_update,update_str,need,check_text,group_teg,fl_const,start_date)
	select ud.cd,ud.unload_file_id,ud.order_num,ud.name,ud.description,ud.unload_data_type_id,ud.length,ud.table_nm,ud.column_nm,ud.column_type,ud.db_table_nm,case when ud.fl_update is null then false else true end,ud.update_str,
	case when ud.need=1 then true when ud.need=3 then false else null end,ud.check_text,ud.group_teg,false,'05.05.2018';
       end if;
    END LOOP;

select setval('ambulance.unload_data_id_seq',(SELECT max(id) FROM unload_data)) into val;

end
$$
